version: 2.1

orbs:
  toolkit: jerus-org/circleci-toolkit@6.0.0
  docker: circleci/docker@3.0.1

jobs:
  test:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: jerusdp/ci-zola
          tag: test
          extra_build_args: --target test
      - run:
          name: Run tests
          command: docker run --rm jerusdp/ci-zola:test

workflows:
  validation:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
    jobs:
      - toolkit/security:
          name: security
          cargo_audit: false
          context:
            - SonarCloud
      - docker/hadolint:
          filters:
            branches:
              ignore: main
      - test:
          filters:
            branches:
              ignore: main
